cat > docker-compose.yml <<EOF
version: '3'
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://172.17.182.134:6875
      - APP_KEY="base64:Ie2B/0u3y3t7u5z5w8y8x/4r4q2p+9o9n7m5k3j1h1g="
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=SecretPassword123
      - DB_DATABASE=bookstackapp
    volumes:
      - ./bookstack_config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=SecretRootPassword123
      - TZ=America/Los_Angeles
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=SecretPassword123
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped

  odoo:
    image: odoo:16.0
    container_name: odoo
    environment:
      - HOST=odoo_db
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - 8069:8069
    depends_on:
      - odoo_db
    restart: unless-stopped

  odoo_db:
    image: postgres:15
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./odoo_db_data:/var/lib/postgresql/data
    restart: unless-stopped
EOF